/*
 Task 28.6: Create idenxes for BOOKS and TABLES.
 */
 -- Indexes for READERS:
CREATE INDEX FIRSTNAME_INDX ON READERS (FIRSTNAME);
CREATE INDEX LASTNAME_INDX ON READERS (LASTNAME);
SHOW INDEXES FROM READERS;
-- Indexes for BOOKS
CREATE INDEX TITLE_INDX ON BOOKS (TITLE);
SHOW INDEXES FROM BOOKS;
-- Query plan:
EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';
